### ISSUE TITLE
Add option to compact single time series

### ISSUE THREAD

**Issue by lamora** [ChronixDB/chronix.server#119]
Right now only a set of time series can be compacted - namely those matching a given joinKey. This approach is slow and inflexibel: you may not want to choose the same ppc value for all time series.

A possible solution is a new parameter: "fq". Here's an example: "chronix/compact?fq=metric:cpu-load AND start:[* TO aTimestamp]". fq identifies all documents to be compacted in standard Lucene query syntax. This approach is very flexibel. It allows the user to compact all documents of single time series - or only a subset (e.g. all data points older than day X).

If the user specifies a joinKey AND a fq, the semantics would be: determine all time series identified by the joinKey. For each time series, compact all documents that match the given fq.

**Comment by FlorianLautenschlager** [comment]
@lamora can i close this issue?

**Comment by lamora** [comment]
Yes :).
