### ISSUE TITLE
Is the kerberos authentification with Solr possible ?

### ISSUE THREAD

**Issue by IDerr** [ChronixDB/chronix.server#136]
Hi,
I want to connect Chronix with my kerberized solr cluster, I have checked the doc, but found nothing.
Any advices ?

Thanks for your work !

**Comment by FlorianLautenschlager** [comment]
Hi, 
have found this in the solr documentation: https://lucene.apache.org/solr/guide/6_6/kerberos-authentication-plugin.html

Looks straight forward.

You want to secure a plain Solr or Chronix cluster?

**Comment by IDerr** [comment]
Sorry, I was on holidays,

I was asking if it's possible to secure the Chronix Cluster with Kerberos.

**Comment by FlorianLautenschlager** [comment]
No problem ;-)

If it is possible to secure a Apache Solr cluster with Kerberos, than it is also possible to secure a Chronix Cluster. Chronix consists of a view plugins that run inside Apache Solr. I have no experience in securing Apache Solr with Kerberos. Sorry.

**Comment by IDerr** [comment]
Oh ok :)

Thanks for the answer
