### ISSUE TITLE
Chronix Server returns unknown field error

### ISSUE THREAD

**Issue by twiechert** [ChronixDB/chronix.server#137]
Hi,

I'm using the OpenTSDB Java client to generate write requests to the chronix backend. Unfortunately, this fails with the error "unknown field 'gridCellId''" at server side. Here is my client code:

```
...
MetricBuilder builder = MetricBuilder.getInstance();
Metric metric = builder.addMetric(MEASUREMENT)
                    .setDataPoint(vehicleLocationReportStatistic.getLastUpdated().getTime(), vehicleLocationReportStatistic.getReportCount()).
                    .addTag("gridCellId", s(vehicleLocationReportStatistic.getVehicleReportInfo().getReportInfo().getGridCellId()));
Response response = httpClient.pushMetrics(builder, ExpectResponse.STATUS_CODE);
...
```

Do I somewhere have to register the tags I'm using in my time series in advance? Thanks four your help!

**Comment by twiechert** [comment]
Thanks @FlorianLautenschlager . I'm new to Solr and was not aware of that file. Thus I was using the bundled schema, which expects dynamic field names to end with "_s".

**Comment by FlorianLautenschlager** [comment]
No problem, you are welcome ;-)
