### ISSUE TITLE
Time series resampling

### ISSUE THREAD

**Issue by twiechert** [ChronixDB/chronix.server#140]
According to the list of available transformation operations, Chronix does currently not support resampling  (or am I missing something?).

Since I need this feature urgently, I would implement it myself. Is there anything important to consider?

I would implement it as a transformation operation that expects the new frequency size, similar to the MovingAverage transformation. Then I would apply the mean to obtain one value per interval, what might be configurable in an improved version.

**Comment by FlorianLautenschlager** [comment]
Hi, currently there is no function to resample time series (sadly). But i would appreciate it, if you implement such a function. It should be straight forward. 

I have create a branch called chronix-resample-function that already provides a skeleton. 

It would be nice to talk about the details / questions in gitter.
