### ISSUE TITLE
What's the Chronix roadmap / status?

### ISSUE THREAD

**Issue by tamoyal** [ChronixDB/chronix.server#147]
I'm currently considering multiple options for a tsdb and I like what Chronix has to offer but given we're a startup, I'm hesitant to use an inactive project. The last commit to Chronix was months ago which isn't necessarily bad except that the [releases are still tagged as beta / pre-release](https://github.com/ChronixDB/chronix.server/releases). Latest tweet is also quite old and links to a broken video. At the same time, it doesn't look like any bugs are open, just enhancements, which is great. Is Chronix still considered an active project / are there plans for future development? Is it considered stable?

**Comment by FlorianLautenschlager** [comment]
Hi, thanks for your question. 

> Chronix still considered an active project

At the moment you can see Chronix as a research project...

> the last commit to Chronix was months ago which isn't necessarily bad except that the releases are still tagged as beta / pre-release.

which is not yet production ready.

We plan to increase the development activity in future and more people will work on Chronix. However it is not a commercial product and will be not in future. 

> are there plans for future development? 

For sure. First we want to release a 1.0 version which will be in two or three months. 
Furthermore we want to implement for features (functions, time series types, ...)

**Comment by tamoyal** [comment]
@FlorianLautenschlager thanks for the update!
