### ISSUE TITLE
Missing Time series 

### ISSUE THREAD

**Issue by Rk85** [ChronixDB/chronix.server#155]
When I query more than 10 timeseries in a single rest call (in my case 12), sometimes I get one or more time series is missing, but I get all the document in solr query always.

My sample query is 

{q=(id:metric1 OR id:metric2 OR id:metric3 OR id:metric4 OR id:metric5 OR id:metric6 OR id:metric7 OR id:metric8 OR id:metric9 OR id:metric10 OR id:metric11 OR id:metric12), tf=start:2019-11-08T09:00:00.000Z AND end:2019-11-08T10:00:00.000Z, fl=mdefId, name}

Can you please help me on this?

**Comment by shridharV** [comment]
Could this be similar to the synchronization issue in the aggregations ?

**Comment by FlorianLautenschlager** [comment]
Hi @Rk85,
thanks for raising this issue.
I will have a look.

**Comment by Rk85** [comment]
Hi Florian,

Please find the re-producing steps below to help you to get to the root cause

Data:
Data contains 15 metrics with 5 data points
[
  {
    "name": "metric1",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric2",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric3",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric4",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric5",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric6",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric7",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric8",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric9",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },  
  {
    "name": "metric10",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric11",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric12",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric13",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric14",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  },
  {
    "name": "metric15",
    "type": "metric",
    "start": 1571633880000,
    "end": 1571635080000,
    "data": "H4sIAAAAAAAAAOPi1Dx7BgRq7Ll4FR4sF9JkgAIuJgNGLk7NWTNBQNOei00AKGvAKMAAAFjYSa0zAAAA"
  } 
]

loop the below chronix stream function for 50 times 
{
   tf: 'start:2019-10-21T04:58:00.000Z AND end:2019-10-21T05:18:00.000Z',
   q:  "name:*",
   cf: "",
   cj: "name",
   fl: '-data,-gUpdatedTs'
}
chronix.stream(httpSolrClient, solrQuery).collect(Collectors.toList())

With loop 50, I found some returned with 14 metrics. Missing metric is random.

**Comment by shridharV** [comment]
👍

**Comment by FlorianLautenschlager** [comment]
Hi, just deployed a new version of chronix including this fix.

**Comment by shridharV** [comment]
Thanks 👍
