### ISSUE TITLE
Chronix Simple Ingestion Interface

### ISSUE THREAD

**Issue by FlorianLautenschlager** [ChronixDB/chronix.server#57]
We should provide a simple ingestion interface for time series data, e.g. pairs of timestamp, value. We should adapt the protocols of InfluxDB, Graphite, ...

**Comment by FlorianLautenschlager** [comment]
We can use GRPC: http://www.grpc.io.

**Comment by FlorianLautenschlager** [comment]
Thx to @phxql for implementing InfluxDB, Graphite, KairosDB, and OpenTSDB HTTP protocols. 
Do we need a custom Chronix format?

**Comment by felixbarny** [comment]
That's great news! Are there plans to mimic the query interface of InfluxDB?

**Comment by FlorianLautenschlager** [comment]
Hi Felix,
no there are currently no plans doing this or something similar.

**Comment by felixbarny** [comment]
Thx for the info. What's the state of the Grafana integration?

**Comment by FlorianLautenschlager** [comment]
The Grafana integration works. There is still some work to do. 
Please ask Grafana related questions in the [chronix.grafana](https://github.com/ChronixDB/chronix.grafana) repository.

**Comment by FlorianLautenschlager** [comment]
We should also add the Prometheus format: https://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by phxql** [comment]
Hey, sounds like a good idea. I'll work on it.

**Comment by FlorianLautenschlager** [comment]
@phxql Can we close this issue, or do you have outstanding work?

**Comment by phxql** [comment]
It's implemented, but i still have to write some documentation.

**Comment by FlorianLautenschlager** [comment]
Great. Thus we can close the issue.
