### ISSUE TITLE
When querying with fq, query handler raises an exception

### ISSUE THREAD

**Issue by redblinkconsulting** [ChronixDB/chronix.server#58]
Steps to reproduce: 
Install chronix-solr-6.0.1
solr start
go to http://localhost:8983/solr/#/chronix/query
q = metric:*Load*
qf = anything you want

solr ui shows:
{
  "responseHeader":{
    "status":400,
    "QTime":4},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"no field name specified in query and no default specified via 'df' param",
    "code":400}}

solr.log shows:
2016-06-07 21:04:59.630 ERROR (qtp110456297-17) [   x:chronix] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: no field name specified in query and no default specified via 'df' param
	at org.apache.solr.parser.SolrQueryParserBase.checkNullField(SolrQueryParserBase.java:700)

**Comment by FlorianLautenschlager** [comment]
Hi, thx for trying Chronix :+1: 

With Chronix 0.2 we have replaced the "ag" and "analysis" tag with "function". Now everything is a function. (see: https://github.com/ChronixDB/chronix.server/blob/master/README.md#function-query

Query the maximum, minimum and count the points:
```
http://localhost:8983/solr/chronix/select?
&q=metric:*Load*
fq=function=max;min;count
```

**Comment by redblinkconsulting** [comment]
Thanks, that worked.
