### ISSUE TITLE
Is there any Chronix client driver for javascript/nodejs

### ISSUE THREAD

**Issue by techwizardg** [ChronixDB/chronix.server#75]
Did not find an email id to write and hence writing it here.

Does chronix provide nodejs/javascript client driver?

**Comment by FlorianLautenschlager** [comment]
Thanks for your question. Sadly there is no nodejs/javascript client at the moment. It is planed to extract a java script client from the grafana datasource plugin (https://github.com/ChronixDB/chronix.grafana).

**Comment by techwizardg** [comment]
Thanks for the immediate reply
