### ISSUE TITLE
Info for a comparison table

### ISSUE THREAD

**Issue by sacreman** [ChronixDB/chronix.server#79]
Hi, I've started a time series comparison table and wondered if you'd be able to help fill it in?

I've only just discovered Chronix and it looks pretty cool. Would be good to have it listed.

https://docs.google.com/spreadsheets/d/1sMQe9oOKhMhIVw9WmuCEWdPtAoccJ4a-IuZv4fXDHxM/edit#gid=0

Happy to expand the table comparison criteria too if you think there's anything else that should be noted in particular about Chronix that would help people choose.

Thanks!

**Comment by FlorianLautenschlager** [comment]
Hi thanks for this.
We will take a closer look within the next days. Nice job!
