### ISSUE TITLE
Frequency detection documentation is confusing.

### ISSUE THREAD

**Issue by TPolzer** [ChronixDB/chronix.server#83]
I just had a look at the frequency detection code to find out what its purpose is.
Reading the documentation is not very enlightening: `Detects if a points occurs multiple times within a defined time range` 

Reading the code, doesn't really help either:
- It takes multiple time series as arguments, but only looks at the first one.
- It uses the `List<Long> currentWindow` as a counter (just the size, contents irrelevant).
- It seems to subdivide a timeseries into chunks just smaller than `windowSize` minutes in duration and returns true if a chunk has at least `windowThreshold` more observations than its predecessor.

**Comment by FlorianLautenschlager** [comment]
I agree - the documentation at this point is poor...

The frequency detector splits a time series into windows, counts the data points, and checks if the delta
between two consecutive windows is above a predefined threshold.

**Comment by FlorianLautenschlager** [comment]
Also see #42 and #60
